### ISSUE TITLE
Battery capacity is always 0 when using Brainlink Lite with BrainLinkPro SDK 

### ISSUE THREAD

**Issue by h3llafresh** [Macrotellect/BrainLinkPro_Android#2]
Value of batteryCapacity field is always 0 in onBrainWavedata callback, although other values present and work normally. I was using MacrotellectLink_V1.2.jar as SDK and Brainlink Lite as an EEG device.

**Comment by Macrotellect** [comment]
Sorry, BrainLink Lite&nbsp;does not support displaying batteryCapacity.&nbsp;If you have more questions, please contact ***@***.***


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Macrotellect/BrainLinkPro_Android"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月15日(星期四) 下午4:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Macrotellect/BrainLinkPro_Android] Battery capacity is always 0 when using Brainlink Lite with BrainLinkPro SDK  (Issue #2)





 
Value of batteryCapacity field is always 0 in onBrainWavedata callback, although other values present and work normally. I was using MacrotellectLink_V1.2.jar as SDK and Brainlink Lite as an EEG device.

**Comment by h3llafresh** [comment]
Ok, thanks
